### ISSUE TITLE
Affiliate Übersicht ist nicht angepasst

### ISSUE THREAD

**Issue by kxckingTimm** [sluhtie/Novacloud-Catppuccin-Theme#1]
Bitte das Affiliate Widget im Dashboard auch anpassen.

![firefox_DuJrlykDNb](https://github.com/user-attachments/assets/193db771-d4dc-426f-ac09-d340d82c6695)

**Comment by kxckingTimm** [comment]
![firefox_gGSetXPbiW](https://github.com/user-attachments/assets/313df8ce-26b1-4dad-8230-cfa01830f489)

**Comment by sluhtie** [comment]
Alles klar mach ich wenn ich heim bin

**Comment by sluhtie** [comment]
Completed in 1.0.3: https://github.com/sluhtie/Novacloud-Catppuccin-Theme/commit/1d3b740d3a3bc5e093b60aa503c5e06540d87eb3
